    -- 야구선수 테이블
    CREATE TABLE PLAYER_BASEBALL (
      PLAYERNUM VARCHAR2(20 BYTE) 
    , TNAME VARCHAR2(20 BYTE) 
    , PNAME VARCHAR2(20 BYTE) 
    , PNUMBER NUMBER(3, 0) 
    , PBIRTH DATE 
    , HEIGHT NUMBER(3, 0) 
    , WEIGHT NUMBER(3, 0) 
    , MAIN VARCHAR2(20 BYTE) 
    , PIMAGE VARCHAR2(100 BYTE) 
    , PCHAR VARCHAR2(100 BYTE) 
    , CLICKUP NUMBER(10, 0) DEFAULT 0 
    , STEP NUMBER(6, 0) DEFAULT 0 
    , PLAY VARCHAR2(20 BYTE) 
    );
